# Generated by Django 2.0 on 2020-12-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='porduct',
            new_name='product',
        ),
    ]
